name: "Build the iOS framework"
on: push

jobs:
  build:
    runs-on: macOS-latest
    steps:
      -
        uses: actions/checkout@v1
      -
        name: "Build the uploaders"
        run: "cd ./uploaders && python3 ./build.py && cd .."
      -
        name: "Get any dependencies"
        run: "go get ."
      -
        name: "Install gomobile"
        run: "go get golang.org/x/mobile/cmd/gomobile && PATH=\"$PATH:$HOME/go/bin\" gomobile init"
      -
        name: "Create the iOS framework"
        run: 'PATH="$PATH:$HOME/go/bin" gomobile bind -target ios'
      -
        name: "zip the framework build"
        run: "zip -vr ios_kernel.zip MagicCapKernel.framework/"
      -
        uses: "actions/upload-artifact@v1"
        with:
          name: "ios_kernel.zip"
          path: "ios_kernel.zip"
