name: Run automated tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: copy to ~/go/src
        run: mkdir -p ~/go/src/magiccap-uploaders-kernel && cp -r . ~/go/src/magiccap-uploaders-kernel && cd ~/go/src/magiccap-uploaders-kernel

      - name: Build the uploaders
        run: cd ./uploaders && python3 ./build.py && cd ..

      - name: Get any dependancies
        run: go get .

      - name: Starts the FTP server
        run: sudo apt install -y python3-setuptools && python3.6 -m pip install pyftpdlib && sudo npm i -g pm2 && pm2 start python3.6 -- ./ftp_server.py

      - name: Run tests
        run: go test ./tests -v
        env:
          ELIXIRE_TOKEN: ${{ secrets.ELIXIRE_TOKEN }}
          RLME_TOKEN: ${{ secrets.RLME_TOKEN }}
          MAGICCAP_INSTALL_ID: ${{ secrets.MAGICCAP_INSTALL_ID }}
          NOVUS_TOKEN: ${{ secrets.NOVUS_TOKEN }}
          FTW_TOKEN: ${{ secrets.FTW_TOKEN }}
          FTP_HOSTNAME: 127.0.0.1
